# Generated by Django 5.0 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmocionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
