# Generated by Django 4.1.13 on 2026-07-13 08:17
# Modified: wrap AlterField in SeparateDatabaseAndState so djongo (MongoDB)
# never executes the unsupported ALTER COLUMN TYPE statement.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emociones', '0001_initial'),
    ]

    operations = [
        # djongo (MongoDB) does not support ALTER COLUMN TYPE.
        # We use SeparateDatabaseAndState so Django's migration state is
        # updated (state_operations) without running any DDL on the database
        # (database_operations is empty — MongoDB is schema-less anyway).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='emociondiaria',
                    name='id',
                    field=models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
    ]
